### ISSUE TITLE
Add this repo to SonarCloud

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/cgbeacon2#255]
@henrikstranneheim and this one as well? Thanks! 🙏🏻

**Comment by henrikstranneheim** [comment]
<img width="1402" alt="Screenshot 2022-08-23 at 11 18 38" src="https://user-images.githubusercontent.com/584738/186121471-6df34961-7386-4627-ad7c-ab44ddbdea42.png">
Fixed

**Comment by northwestwitch** [comment]
Thanks! 🚀
